name: BUILD CI


on:
  workflow_run:
    workflows: ["TEST-REPORT CI"]
    types: [completed]

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build Docker image and Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Jdk 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew -x test clean build

      - name: Test with Gradle
        run: ./gradlew -x test clean build

      - name: Save Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-results
          path: build/libs/*.jar  # 빌드된 결과물 저장gkrl

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-results  # CI에서 업로드한 아티팩트 이름과 동일



