name: Gongbaek CI


on:
  pull_request:
    branches: [ "main"]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Jdk 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew --info test

      - name: Publish Test Results
        uses : EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**./*.xml
            test-results/**./*.trx
            test-results/**./*.json




