name: CD

on:
  workflow_run:
    workflows:
      - BUILD CI  # CI 워크플로 이름
    types:
      - completed


jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Downloads Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-results
          run: ls -R

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/practice:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/practice:latest
    

      - name: Debug workflow event
        run: 'echo "Workflow run triggered for branch: ${{ github.ref }}"'
      - name: deploy appleboy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/practice:latest
            echo "now finished deploy: $(date '+%Y-%m-%d %H:%M:%S')" > finished.txt         
