name: Gongbaek CD


on:
  pull_request:
    branches: [ "main"]


jobs:
  build:
    name: Build Docker image and Push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Jdk 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew -x test clean build

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name : Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/practice:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/practice:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: deploy appleboy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/practice:latest
            echo "now finished" > finished.txt
         
