name: Gongbaek CD

on:
  workflow_run:
    workflows:
      - [Gongbaek CI]  # CI 워크플로 이름
    types:
      - completed

  pull_request:
    branches: [ "main"]


jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: deploy appleboy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/practice:latest
            echo "now finished" > finished.txt
         
