name: CD

on:
  workflow_run:
    workflows:
      - BUILD-CI  # CI 워크플로 이름
    types:
      - completed
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: deploy appleboy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/practice:latest
            echo "now finished deploy: $(date '+%Y-%m-%d %H:%M:%S')" > finished.txt         
